common:  
  env_secrets:
    - envName: COMMON_CUSTOM_SECRET
      secretName: common-custom-secret
      secretKey: secret
    - envName: COMMON_CUSTOM_PASSWORD
      secretName: common-custom-secret
      secretKey: password
kibana:
  env_secrets:
    - envName: KIBANA_CUSTOM_SECRET
      secretName: kibana-custom-secret
      secretKey: secret
    - envName: KIBANA_CUSTOM_PASSWORD
      secretName: kibana-custom-secret
      secretKey: password
