common:  
  secrets:
    - envName: COMMON_CUSTOM_SECRET
      secretName: common-custom-secret
      secretKey: password
    - envName: COMMON_CUSTOM_KEY
      secretName: common-custom-secret
      secretKey: key2      

kibana:
  secrets:
    - envName: KIBANA_CUSTOM_SECRET
      secretName: kibana-custom-secret
      secretKey: password
    - envName: KIBANA_CUSTOM_KEY2
      secretName: kibana-custom-secret
      secretKey: key2      

