apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-sgadmin
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}-sgadmin
    role: sgadmin
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: {{ template "fullname" . }}
      role: sgadmin
  template:
    metadata:
      labels:
        release: "{{ .Release.Name }}"
        app: {{ template "fullname" . }}
        component: {{ template "fullname" . }}
        role: sgadmin
      {{ if .Values.common.update_sgconfig_on_change }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/searchguard-configmap.yaml") . | sha256sum }}
      {{ end }}
    spec:
      subdomain: {{ template "fullname" . }}
      serviceAccountName: {{ template "fullname" . }}
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: sgadmin-init
          image: "floragunncom/sg-sgadmin:{{ .Values.common.elkversion }}-{{ .Values.common.sgversion }}"
          imagePullPolicy: {{ .Values.common.pullPolicy }}
          env:
            - name: DISCOVERY_SERVICE
              value: {{ template "fullname" . }}-discovery.{{ .Release.Namespace }}.svc
          volumeMounts:
            - mountPath: /root/sgconfig/
              name: searchguard-config
            - name: secret-volume
              readOnly: true
              mountPath: /root/sgcerts/
          command:
            - sh
            - -c
            - |
                #!/usr/bin/env bash -e

                kubectl get secrets | grep {{ template "fullname" . }}-passwd-secret
                
                if [ "$?" == "1" ]; then

                cat >"{{ template "fullname" . }}-root-ca.yml" <<EOL
                ca:
                  root:
                      dn: CN={{ template "fullname" . }}-root-ca,OU=CA,O=Example Com\, Inc.,DC=example,DC=com
                      keysize: 2048
                      validityDays: 365
                      pkPassword: none
                      file: root-ca.pem
                EOL

                /root/tlstool/tools/sgtlstool.sh -ca -v -c "{{ template "fullname" . }}-root-ca.yml" -t /tmp/

                cat >"{{ template "fullname" . }}-root-ca-sec.yaml" <<EOL
                apiVersion: v1
                kind: Secret
                metadata:
                  labels:
                    app: {{ template "fullname" . }}
                    component: sginit
                    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
                    heritage: "{{ .Release.Service }}"
                    release: "{{ .Release.Name }}"
                    sgrootcacert: "true"
                  name: {{ template "fullname" . }}-root-ca-secret
                  namespace: {{ .Release.Namespace }}
                type: Opaque
                data:
                  crt.pem: $(cat /tmp/root-ca.pem | base64 -w0)
                  key.pem: $(cat /tmp/root-ca.key | base64 -w0)
                EOL

                cat "{{ template "fullname" . }}-root-ca-sec.yaml"

                kubectl apply -f "{{ template "fullname" . }}-root-ca-sec.yaml"

                cat >"{{ template "fullname" . }}-admin-cert.yml" <<EOL
                ca:
                  root:
                      file: root-ca.pem
                clients:
                  - name: sgadmin
                    admin: true
                    dn: CN=sgadmin,OU=Ops,O=Example Com\, Inc.,DC=example,DC=com
                EOL

                /root/tlstool/tools/sgtlstool.sh -crt -v -c "{{ template "fullname" . }}-admin-cert.yml" -t /tmp/

                cat >"{{ template "fullname" . }}-admin-cert-sec.yaml" <<EOL
                apiVersion: v1
                kind: Secret
                metadata:
                  labels:
                    app: {{ template "fullname" . }}
                    component: sginit
                    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
                    heritage: "{{ .Release.Service }}"
                    release: "{{ .Release.Name }}"
                  name: {{ template "fullname" . }}-admin-cert-secret
                  namespace: {{ .Release.Namespace }}
                type: Opaque
                data:
                  crt.pem: $(cat /tmp/sgadmin.pem | base64 -w0)
                  key.pem: $(cat /tmp/sgadmin.key | base64 -w0)
                  root-ca.pem: $(cat /tmp/root-ca.pem | base64 -w0)
                EOL

                kubectl patch secret {{ template "fullname" . }}-admin-cert-secret -p="{\"data\":{\"crt.pem\": \"$(cat /tmp/sgadmin.pem | base64 -w0)\", \"key.pem\": \"$(cat /tmp/sgadmin.key | base64 -w0)\", \"root-ca.pem\": \"$(cat /tmp/root-ca.pem | base64 -w0)\"}}" -v=5

                #kubectl apply -f "{{ template "fullname" . }}-admin-cert-sec.yaml"
                echo "Will generate {{ template "fullname" . }}-passwd-secret"

                export kibana_cookie_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"
                export admin_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"
                export kibana_ro_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"
                export kibana_server_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"

                cat >"{{ template "fullname" . }}-passwd-secret.yaml" <<EOL
                apiVersion: v1
                kind: Secret
                metadata:
                  labels:
                    app: {{ template "fullname" . }}
                    component: sginit
                    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
                    heritage: "{{ .Release.Service }}"
                    release: "{{ .Release.Name }}"
                    sgpwdsecret: "true"
                  name: {{ template "fullname" . }}-passwd-secret
                  namespace: {{ .Release.Namespace }}
                type: Opaque
                data:
                  kibana_cookie_pwd: $(echo -n $kibana_cookie_pwd | base64 -w0)
                  kibana_server_pwd: $(echo -n $kibana_server_pwd | base64 -w0)
                  admin_pwd: $(echo -n $admin_pwd | base64 -w0)
                  kibana_ro_pwd: $(echo -n $kibana_ro_pwd | base64 -w0)
                EOL

                kubectl apply -f "{{ template "fullname" . }}-passwd-secret.yaml"
                cp /root/sgconfig/sg_* /tmp/

                sed -i -e "s#_RPLC_ADMIN_HASH#$(/root/sgadmin/tools/hash.sh -env admin_pwd)#g" /tmp/sg_internal_users.yml
                sed -i -e "s#_RPLC_KIBANA_RO_HASH#$(/root/sgadmin/tools/hash.sh -env kibana_ro_pwd)#g" /tmp/sg_internal_users.yml
                sed -i -e "s#_RPLC_KIBANA_SERVER_HASH#$(/root/sgadmin/tools/hash.sh -env kibana_server_pwd)#g" /tmp/sg_internal_users.yml

                echo "Executing sgadmin first time ..."
                /root/sgadmin/tools/sgadmin.sh -h $DISCOVERY_SERVICE -cd /tmp/ -cn {{ .Values.common.cluster_name }} -key /root/sgcerts/key.pem -cert /root/sgcerts/crt.pem -cacert /root/sgcerts/root-ca.pem
                RET=$?
                echo "Result $RET"
                exit $RET

                else

                {{ if .Values.common.update_sgconfig_on_change }}
                echo "{{ template "fullname" . }}-passwd-secret exists"

                export admin_pwd="$(kubectl get secrets {{ template "fullname" . }}-passwd-secret -o jsonpath="{.data.admin_pwd}" | base64 -d)"
                export kibana_ro_pwd="$(kubectl get secrets {{ template "fullname" . }}-passwd-secret -o jsonpath="{.data.kibana_ro_pwd}" | base64 -d)"
                export kibana_server_pwd="$(kubectl get secrets {{ template "fullname" . }}-passwd-secret -o jsonpath="{.data.kibana_server_pwd}" | base64 -d)"
                
                cp /root/sgconfig/sg_* /tmp/

                sed -i -e "s#_RPLC_ADMIN_HASH#$(/root/sgadmin/tools/hash.sh -env admin_pwd)#g" /tmp/sg_internal_users.yml
                sed -i -e "s#_RPLC_KIBANA_RO_HASH#$(/root/sgadmin/tools/hash.sh -env kibana_ro_pwd)#g" /tmp/sg_internal_users.yml
                sed -i -e "s#_RPLC_KIBANA_SERVER_HASH#$(/root/sgadmin/tools/hash.sh -env kibana_server_pwd)#g" /tmp/sg_internal_users.yml

                echo "Executing sgadmin to update the configs ..."
                /root/sgadmin/tools/sgadmin.sh -h $DISCOVERY_SERVICE -cd /tmp/ -cn {{ .Values.common.cluster_name }} -key /root/sgcerts/key.pem -cert /root/sgcerts/crt.pem -cacert /root/sgcerts/root-ca.pem
                RET=$?
                echo "Result $RET"
                exit $RET
                {{ end }}
                :
                fi
          resources:
            limits:
              cpu: "500m"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
      containers:
      - name: sgadmin
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: "floragunncom/sg-sgadmin:{{ .Values.common.elkversion }}-{{ .Values.common.sgversion }}"
        imagePullPolicy: {{ .Values.common.pullPolicy }}
        env:
        - name: DISCOVERY_SERVICE
          value: {{ template "fullname" . }}-discovery.{{ .Release.Namespace }}.svc
        resources:
        volumeMounts:
        - mountPath: /root/sgconfig/
          name: searchguard-config
        - name: secret-volume
          readOnly: true
          mountPath: /root/sgcerts/
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ template "fullname" . }}-admin-cert-secret
        - configMap:
            name: {{ template "fullname" . }}-searchguard-config
          name: searchguard-config
